---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update system
      pacman:
        update_cache: true
        upgrade: true
      become: true
      changed_when: false
    - name: Reboot for kernel updates
      reboot:
